Repository joncampbell123/dosbox-x, pull requests merged in 2019-11, with the labels that each got.

#1311 Windows Explorer context menu entries
  windows_explorer_context_menu_installer.bat
  windows_explorer_context_menu_uninstaller.bat
Labels: enhancement, platform: Windows, topic: Windows

#1327 Brighter properties + line break for clarity.
  src/gui/sdl_gui.cpp
Labels: enhancement, topic: video

#1329 Fix for HELP's "Message not Found!"
  src/misc/messages.cpp
  src/shell/shell_cmds.cpp
Labels: documentation

#1334 Fix Cppcheck warnings
  src/aviwriter/avi_writer.cpp
  src/aviwriter/riff.cpp
  src/cpu/core_full/load.h
  src/cpu/cpu.cpp
  src/debug/debug.cpp
  src/dos/dev_con.h
  src/dos/dos.cpp
  src/dos/dos_files.cpp
  src/dos/dos_programs.cpp
  src/dos/dos_tables.cpp
  src/dos/drive_fat.cpp
  src/gui/midi_win32.h
  src/gui/render_templates_sai.h
  src/gui/sdl_mapper.cpp
  src/gui/sdlmain.cpp
  src/hardware/dbopl.cpp
  src/hardware/dma.cpp
  src/hardware/keyboard.cpp
  src/hardware/pic.cpp
  src/hardware/reSID/spline.h
  src/hardware/vga.cpp
  src/hardware/vga_draw.cpp
  src/hardware/vga_other.cpp
  src/hardware/vga_xga.cpp
  src/hardware/voodoo_emu.cpp
  src/hardware/voodoo_opengl.cpp
  src/ints/bios.cpp
  src/ints/bios_disk.cpp
  src/ints/ems.cpp
  src/libs/gui_tk/gui_tk.cpp
  src/misc/programs.cpp
  src/mt32/Part.cpp
  src/shell/shell.cpp
  src/shell/shell_cmds.cpp
  src/shell/shell_misc.cpp
Labels: code base, enhancement
